# Generated by Django 3.1.3 on 2020-11-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=True)),
                ('site_id', models.CharField(max_length=20)),
                ('site_pw', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=40)),
                ('birthday', models.DateTimeField()),
                ('reseve_num', models.IntegerField()),
                ('car_num', models.IntegerField()),
                ('is_pad', models.BooleanField(default=True)),
                ('car_cvc_num', models.IntegerField()),
                ('card_experiment', models.IntegerField()),
                ('car_password', models.IntegerField()),
                ('room_person_cnt', models.IntegerField()),
                ('room_type', models.CharField(max_length=20)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('room_service_fee', models.IntegerField()),
                ('guest_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=1)),
                ('birthday', models.DateTimeField()),
                ('email', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=50)),
                ('hire_date', models.DateTimeField()),
                ('salary', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
