# Generated by Django 3.1.3 on 2020-11-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=True)),
                ('site_id', models.CharField(max_length=20)),
                ('site_pw', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nation', models.CharField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('car_num', models.IntegerField(blank=True, null=True)),
                ('is_pad', models.BooleanField(blank=True, default=True, null=True)),
                ('card_cvc_num', models.IntegerField(blank=True, null=True)),
                ('card_experiment', models.IntegerField(blank=True, null=True)),
                ('card_password', models.IntegerField(blank=True, null=True)),
                ('room_person_cnt', models.IntegerField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, max_length=20, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('room_service_fee', models.IntegerField(blank=True, null=True)),
                ('guest_point', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guest',
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('work_check', models.BooleanField(default=False)),
                ('is_emergency', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('fee', models.IntegerField()),
                ('payment_num', models.IntegerField()),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('nation', models.CharField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(choices=[
                 ('MALE', 'Male'), ('FEMALE', 'Female')], default='Male', max_length=6)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('had_annual_leave', models.IntegerField(default=0)),
                ('department', models.CharField(choices=[('Cleaning Dept', 'Cleaning Dept'), ('Food Beverage Dept', 'Food Beverage Dept'), ('Front Office Dept', 'Front Office Dept'), ('Customer Response Dept', 'Customer Response Dept'), (
                    'Technical Support Dept', 'Technical Support Dept'), ('Parking Dept', 'Parking Department'), ('Purchasing Dept', 'Purchasing Department'), ('Center', 'Center Department'), ('Executive', 'Executive')], default='None', max_length=25)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('finish_time', models.DateField()),
                ('accept', models.BooleanField(default=False)),
                ('staff_id', models.ForeignKey(db_column='staff_id',
                                               on_delete=django.db.models.deletion.CASCADE, to='UserApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('finish_time', models.DateTimeField(null=True)),
                ('work_type', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('accept', models.BooleanField(null=True)),
                ('staff_id', models.ForeignKey(db_column='staff_id',
                                               on_delete=django.db.models.deletion.CASCADE, to='UserApp.staff')),
            ],
        ),
    ]
