# Generated by Django 3.1.3 on 2020-12-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, default='0,0,0', max_length=100, null=True),
        ),
    ]
