# Generated by Django 3.1.3 on 2020-11-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20201117_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='car_cvc_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='car_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='car_password',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='card_experiment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_point',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='is_pad',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nation',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='reseve_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='room_person_cnt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='room_service_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='room_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
