# Generated by Django 3.1.3 on 2020-11-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20201117_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_check', models.BooleanField(default=False)),
                ('is_emergency', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('fee', models.IntegerField()),
                ('payment_num', models.IntegerField()),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.AlterModelTable(
            name='guest',
            table='guest',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
