# Generated by Django 3.1.3 on 2020-11-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_auto_20201117_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=models.IntegerField(default=0),
        ),
    ]
