# Generated by Django 3.1.3 on 2020-11-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_staff_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='car_cvc_num',
            new_name='card_cvc_num',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='car_password',
            new_name='card_password',
        ),
    ]
