# Generated by Django 3.1.3 on 2020-11-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_auto_20201119_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
    ]
