# Generated by Django 3.1.3 on 2020-11-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_remove_staff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('CLE', 'Cleaning'), ('TSD', 'Technical Support Department'), ('CRD', 'Customer Response Department')], default='None', max_length=3),
        ),
    ]
