# Generated by Django 3.1.1 on 2020-11-22 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_auto_20201119_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('work_type', models.CharField(max_length=50)),
                ('had_annual_leave', models.IntegerField()),
                ('description', models.TextField()),
                ('accecpt', models.BooleanField()),
                ('staff_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, to='UserApp.staff')),
            ],
        ),
    ]
