# Generated by Django 3.1.3 on 2020-11-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_id',
            new_name='stf_id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff_id',
            field=models.ForeignKey(db_column='stf_id', on_delete=django.db.models.deletion.CASCADE, to='UserApp.staff'),
        ),
    ]
