# Generated by Django 3.1.3 on 2020-11-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_auto_20201123_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='stf_id',
            new_name='staff_id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff_id',
            field=models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, to='UserApp.staff'),
        ),
    ]
