# Generated by Django 3.1.3 on 2020-11-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_auto_20201123_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='had_annual_leave',
        ),
        migrations.AddField(
            model_name='staff',
            name='had_annual_leave',
            field=models.IntegerField(default=0),
        ),
    ]
