# Generated by Django 3.1.3 on 2020-11-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_auto_20201123_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('CLE', 'Cleaning'), ('TSD', 'Technical Support Department'), ('CRD', 'Customer Response Department'), ('MAN', 'Manager Department')], default='None', max_length=3),
        ),
    ]
