# Generated by Django 3.1.1 on 2020-11-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_staffleave'),
        ('UserApp', '0010_auto_20201122_2056'),
    ]

    operations = [
    ]
