# Generated by Django 3.1.1 on 2020-11-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_merge_20201123_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffleave',
            name='accecpt',
        ),
        migrations.AddField(
            model_name='staffleave',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
