# Generated by Django 3.1.3 on 2020-11-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_merge_20201123_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='had_annual_leave',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='salary',
        ),
        migrations.AlterModelTable(
            name='staff',
            table=None,
        ),
    ]
