# Generated by Django 3.1.1 on 2020-11-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_auto_20201124_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('Cleaning Dept', 'Cleaning Dept'), ('Food Beverage Dept', 'Food Beverage Dept'), ('Front Office Dept', 'Front Office Dept'), ('Customer Response Dept', 'Customer Response Dept'), ('Technical Support Dept', 'Technical Support Dept'), ('Parking Dept', 'Parking Department'), ('Purchasing Dept', 'Purchasing Department'), ('Center', 'Center Department'), ('Executive', 'Executive')], default='None', max_length=25),
        ),
    ]
