# Generated by Django 3.1.3 on 2020-11-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_auto_20201124_1417'),
        ('UserApp', '0018_auto_20201124_1540'),
    ]

    operations = [
    ]
