# Generated by Django 3.1.1 on 2020-11-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0020_auto_20201124_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleave',
            name='finish_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='start_time',
            field=models.DateField(),
        ),
    ]
