# Generated by Django 3.1.3 on 2020-11-25 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0008_auto_20201125_0945'),
        ('UserApp', '0021_auto_20201125_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='reseve_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RoomApp.booking'),
        ),
    ]
