# Generated by Django 3.1.1 on 2020-11-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0021_auto_20201126_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='accecpt',
            new_name='accept',
        ),
    ]
