# Generated by Django 3.1.1 on 2020-11-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0022_auto_20201126_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffLeave',
        ),
    ]
