# Generated by Django 3.1.1 on 2020-11-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0023_delete_staffleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('finish_time', models.DateField()),
                ('accept', models.BooleanField(default=False)),
                ('staff_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, to='UserApp.staff')),
            ],
        ),
    ]
