# Generated by Django 3.1.1 on 2020-11-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0024_staffleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='accept',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='work_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
