# Generated by Django 3.1.3 on 2020-11-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0025_auto_20201126_1318'),
        ('UserApp', '0023_auto_20201125_1130'),
    ]

    operations = [
    ]
