# Generated by Django 3.1.3 on 2020-11-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RoomApp', '0002_auto_20201117_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pad_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomApp.room')),
            ],
        ),
        migrations.CreateModel(
            name='TurnDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_turndown', models.BooleanField(default=False)),
                ('pad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PadApp.pad')),
            ],
        ),
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_roomservice', models.BooleanField(default=False)),
                ('roomservice_type', models.CharField(choices=[('PNS', 'PASTAS & SANDWICHES'), ('GRILL', 'FROM THE GRILL'), ('DES', 'DESSERT')], max_length=5)),
                ('menu_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('pad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PadApp.pad')),
            ],
        ),
        migrations.CreateModel(
            name='Dnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dnd', models.BooleanField(default=False)),
                ('pad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PadApp.pad')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complain', models.BooleanField(default=False)),
                ('complain_type', models.CharField(choices=[('ITEM', '물품 요청'), ('BD', '기계 오작동'), ('SANI', '위생 불만족'), ('ETC', '기타')], max_length=4)),
                ('content', models.TextField(max_length=800)),
                ('pad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PadApp.pad')),
            ],
        ),
    ]
