# Generated by Django 3.1.3 on 2020-11-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomservice_type', models.CharField(choices=[('PNS', 'PASTAS & SANDWICHES'), ('GRILL', 'FROM THE GRILL'), ('DES', 'DESSERT')], max_length=5)),
                ('menu_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='roomservice',
            name='menu_name',
        ),
        migrations.RemoveField(
            model_name='roomservice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='roomservice',
            name='roomservice_type',
        ),
        migrations.AddField(
            model_name='roomservice',
            name='select_roomservice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PadApp.roomservicetype'),
        ),
    ]
