# Generated by Django 3.1.3 on 2020-11-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservice',
            name='select_roomservice',
        ),
        migrations.AddField(
            model_name='roomservice',
            name='selected_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PadApp.roomservicetype'),
        ),
    ]
