# Generated by Django 3.1.3 on 2020-11-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0002_auto_20201118_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservicetype',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
