# Generated by Django 3.1.3 on 2020-11-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0002_auto_20201201_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
