# Generated by Django 3.1.3 on 2020-11-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0003_roomservice_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomservice',
            old_name='created',
            new_name='created_date',
        ),
    ]
