# Generated by Django 3.1.3 on 2020-12-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0004_auto_20201201_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='roomservice_num',
            field=models.IntegerField(default=0),
        ),
    ]
