# Generated by Django 3.1.3 on 2020-11-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0005_roomservicetype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservicetype',
            name='image',
            field=models.ImageField(blank=True, upload_to='roomservice'),
        ),
    ]
