# Generated by Django 3.1.3 on 2020-11-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0006_roomservicetype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservicetype',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
