# Generated by Django 3.1.3 on 2020-11-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0008_roomservice_roomservice_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
