# Generated by Django 3.1.3 on 2020-11-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0009_roomservice_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomservicetype',
            old_name='roomservice_type',
            new_name='menu_type',
        ),
    ]
