# Generated by Django 3.1.3 on 2020-11-26 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0023_auto_20201125_1130'),
        ('PadApp', '0009_roomservice_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomservicetype',
            old_name='roomservice_type',
            new_name='menu_type',
        ),
        migrations.AddField(
            model_name='roomservice',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='UserApp.guest'),
        ),
        migrations.AlterField(
            model_name='roomservice',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
