# Generated by Django 3.1.3 on 2020-11-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0010_auto_20201126_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservicetype',
            name='count',
        ),
        migrations.AlterField(
            model_name='roomservice',
            name='roomservice_num',
            field=models.IntegerField(auto_created=True),
        ),
    ]
