# Generated by Django 3.1.3 on 2020-11-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0010_auto_20201126_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
