# Generated by Django 3.1.3 on 2020-11-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0023_auto_20201125_1130'),
        ('PadApp', '0011_auto_20201126_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.guest'),
        ),
    ]
