# Generated by Django 3.1.3 on 2020-11-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0012_auto_20201126_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservice',
            name='roomservice_num',
        ),
        migrations.RemoveField(
            model_name='roomservice',
            name='select_roomservice',
        ),
        migrations.AddField(
            model_name='roomservicetype',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PadApp.roomservicetype')),
            ],
        ),
        migrations.AddField(
            model_name='roomservice',
            name='items',
            field=models.ManyToManyField(to='PadApp.OrderItem'),
        ),
    ]
