# Generated by Django 3.1.3 on 2020-11-16 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('room_limit', models.IntegerField()),
                ('room_fee', models.IntegerField()),
                ('on_use', models.BooleanField()),
                ('category', models.CharField(choices=[('DEL', 'DELUXE'), ('KIN', 'KING'), ('QUE', 'QUEEN')], max_length=3)),
                ('beds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=10)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('booking_roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomApp.room')),
                ('booking_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_cvc_num', models.PositiveIntegerField()),
                ('card_experiment', models.PositiveIntegerField()),
                ('card_password', models.PositiveIntegerField()),
                ('bill_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomApp.room')),
            ],
        ),
    ]
