# Generated by Django 3.1.3 on 2020-11-28 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('room_limit', models.IntegerField()),
                ('room_fee', models.IntegerField()),
                ('on_use', models.BooleanField()),
                ('category', models.CharField(choices=[('STD', 'STANDARD'), ('SUP', 'SUPERIOR'), ('DEL', 'DELUXE'), ('EXC', 'EXECUTIVE'), ('STE', 'SUITE')], max_length=10)),
                ('beds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('check_in_date', models.DateTimeField(auto_now=True)),
                ('check_out_date', models.DateTimeField(auto_now=True)),
                ('booking_roomid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RoomApp.room')),
                ('booking_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_cvc_num', models.PositiveIntegerField()),
                ('card_experiment', models.PositiveIntegerField()),
                ('card_password', models.PositiveIntegerField()),
                ('bill_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomApp.room')),
            ],
        ),
    ]
