# Generated by Django 3.1.3 on 2020-11-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0002_auto_20201130_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
