# Generated by Django 3.1.3 on 2020-11-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0003_auto_20201119_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_roomid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RoomApp.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
