# Generated by Django 3.1.3 on 2020-11-25 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0004_auto_20201121_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
    ]
