# Generated by Django 3.1.3 on 2020-11-25 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0008_roomservice_roomservice_num'),
        ('RoomApp', '0005_remove_booking_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='screen_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PadApp.pad'),
            preserve_default=False,
        ),
    ]
