# Generated by Django 3.1.3 on 2020-11-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0006_room_screen_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='screen_id',
        ),
    ]
