# Generated by Django 3.1.3 on 2020-11-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0006_auto_20201130_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
