# Generated by Django 3.1.3 on 2020-11-30 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PadApp', '0001_initial'),
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='product_request_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='roomservice_num',
        ),
        migrations.AddField(
            model_name='request',
            name='roomservice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PadApp.roomservice'),
        ),
        migrations.DeleteModel(
            name='ProductRequest',
        ),
    ]
