# Generated by Django 3.1.3 on 2020-11-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_auto_20201119_1621'),
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='charged_robot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charged_robot_id', to='UserApp.robot'),
        ),
        migrations.AlterField(
            model_name='request',
            name='charged_staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charged_staff_id', to='UserApp.staff'),
        ),
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='product_request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskApp.productrequest'),
        ),
        migrations.AlterField(
            model_name='request',
            name='send_guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_guest_id', to='UserApp.guest'),
        ),
        migrations.AlterField(
            model_name='request',
            name='send_staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_staff_id', to='UserApp.staff'),
        ),
    ]
