# Generated by Django 3.1.3 on 2020-12-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_auto_20201130_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='roomservice_id',
        ),
        migrations.AddField(
            model_name='request',
            name='roomservice_num',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
