# Generated by Django 3.1.3 on 2020-11-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_auto_20201122_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='roomservice_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
