# Generated by Django 3.1.3 on 2020-11-25 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0004_auto_20201125_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
