# Generated by Django 3.1.3 on 2020-11-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0005_request_completed_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='completed_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
